Traceback (most recent call last):
  File "/home/celien/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/celien/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/celien/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/celien/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/celien/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/celien/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/celien/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from board import Board
from strategy import AlphaBeta, Human
from main import play_game
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mboard[39;00m [38;5;28;01mimport[39;00m Board
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstrategy[39;00m [38;5;28;01mimport[39;00m AlphaBeta, Human
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmain[39;00m [38;5;28;01mimport[39;00m play_game

File [0;32m~/Documents/ProyectoAI1/docs/main.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdocs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mboard[39;00m [38;5;28;01mimport[39;00m Board
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdocs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstrategy[39;00m [38;5;28;01mimport[39;00m Human, Random, Greedy, MinMax, AlphaBeta
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mcheck_winner[39m(board):

[0;31mModuleNotFoundError[0m: No module named 'docs.board'

